theme = "dark_plus"

[editor]
line-number = "absolute"
mouse = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
X = "select_line_above"
x = "select_line_below"
A-C-G = [ ":hsplit-new", ":lang diff", ":insert-output git diff | delta" ]

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"
